[build]
  functions = "netlify-functions"  # Specifies the folder where functions are stored
  publish = "dist/edominations-tools"                 # Tells Netlify to publish the contents of the `dist` folder

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true
