export const countries = [
  {"id": 1, "name": "Afghanistan", "value": "Afghanistan"},
  {"id": 2, "name": "Albania", "value": "Albania"},
  {"id": 3, "name": "Algeria", "value": "Algeria"},
  {"id": 4, "name": "Argentina", "value": "Argentina"},
  {"id": 5, "name": "Armenia", "value": "Armenia"},
  {"id": 6, "name": "Australia", "value": "Australia"},
  {"id": 7, "name": "Austria", "value": "Austria"},
  {"id": 8, "name": "Azerbaijan", "value": "Azerbaijan"},
  {"id": 9, "name": "Belarus", "value": "Belarus"},
  {"id": 10, "name": "Belgium", "value": "Belgium"},
  {"id": 11, "name": "Bolivia", "value": "Bolivia"},
  {"id": 12, "name": "Bosnia and Herzegovina", "value": "Bosnia-and-Herzegovina"},
  {"id": 13, "name": "Brazil", "value": "Brazil"},
  {"id": 14, "name": "Bulgaria", "value": "Bulgaria"},
  {"id": 15, "name": "Canada", "value": "Canada"},
  {"id": 16, "name": "Chile", "value": "Chile"},
  {"id": 17, "name": "China", "value": "China"},
  {"id": 18, "name": "Colombia", "value": "Colombia"},
  {"id": 19, "name": "Croatia", "value": "Croatia"},
  {"id": 20, "name": "Cuba", "value": "Cuba"},
  {"id": 21, "name": "Cyprus", "value": "Cyprus"},
  {"id": 22, "name": "Czech Republic", "value": "Czech-Republic"},
  {"id": 23, "name": "Denmark", "value": "Denmark"},
  {"id": 24, "name": "Ecuador", "value": "Ecuador"},
  {"id": 25, "name": "Egypt", "value": "Egypt"},
  {"id": 26, "name": "Estonia", "value": "Estonia"},
  {"id": 27, "name": "Finland", "value": "Finland"},
  {"id": 28, "name": "France", "value": "France"},
  {"id": 29, "name": "Georgia", "value": "Georgia"},
  {"id": 30, "name": "Germany", "value": "Germany"},
  {"id": 31, "name": "Greece", "value": "Greece"},
  {"id": 32, "name": "Hungary", "value": "Hungary"},
  {"id": 33, "name": "India", "value": "India"},
  {"id": 34, "name": "Indonesia", "value": "Indonesia"},
  {"id": 35, "name": "Iran", "value": "Iran"},
  {"id": 36, "name": "Ireland", "value": "Ireland"},
  {"id": 37, "name": "Israel", "value": "Israel"},
  {"id": 38, "name": "Italy", "value": "Italy"},
  {"id": 39, "name": "Japan", "value": "Japan"},
  {"id": 40, "name": "Latvia", "value": "Latvia"},
  {"id": 41, "name": "Lithuania", "value": "Lithuania"},
  {"id": 42, "name": "Luxembourg", "value": "Luxembourg"},
  {"id": 43, "name": "Malaysia", "value": "Malaysia"},
  {"id": 44, "name": "Mexico", "value": "Mexico"},
  {"id": 45, "name": "Montenegro", "value": "Montenegro"},
  {"id": 46, "name": "Netherlands", "value": "Netherlands"},
  {"id": 47, "name": "New Zealand", "value": "New-Zealand"},
  {"id": 48, "name": "North Korea", "value": "North-Korea"},
  {"id": 49, "name": "Norway", "value": "Norway"},
  {"id": 50, "name": "Pakistan", "value": "Pakistan"},
  {"id": 51, "name": "Paraguay", "value": "Paraguay"},
  {"id": 52, "name": "Peru", "value": "Peru"},
  {"id": 53, "name": "Poland", "value": "Poland"},
  {"id": 54, "name": "Portugal", "value": "Portugal"},
  {"id": 55, "name": "Republic of China (Taiwan)", "value": "Taiwan"},
  {"id": 56, "name": "North Macedonia", "value": "North-Macedonia"},
  {"id": 57, "name": "Republic of Moldova", "value": "Moldova"},
  {"id": 58, "name": "Romania", "value": "Romania"},
  {"id": 59, "name": "Russia", "value": "Russia"},
  {"id": 60, "name": "Saudi Arabia", "value": "Saudi-Arabia"},
  {"id": 61, "name": "Serbia", "value": "Serbia"},
  {"id": 62, "name": "Singapore", "value": "Singapore"},
  {"id": 63, "name": "Slovakia", "value": "Slovakia"},
  {"id": 64, "name": "Slovenia", "value": "Slovenia"},
  {"id": 65, "name": "South Africa", "value": "South-Africa"},
  {"id": 66, "name": "South Korea", "value": "South-Korea"},
  {"id": 67, "name": "Spain", "value": "Spain"},
  {"id": 68, "name": "Sweden", "value": "Sweden"},
  {"id": 69, "name": "Switzerland", "value": "Switzerland"},
  {"id": 70, "name": "Thailand", "value": "Thailand"},
  {"id": 71, "name": "Tunisia", "value": "Tunisia"},
  {"id": 72, "name": "Turkey", "value": "Turkey"},
  {"id": 73, "name": "Ukraine", "value": "Ukraine"},
  {"id": 74, "name": "United Arab Emirates", "value": "United-Arab-Emirates"},
  {"id": 75, "name": "United Kingdom", "value": "United-Kingdom"},
  {"id": 76, "name": "United States of America", "value": "United-States"},
  {"id": 77, "name": "Uruguay", "value": "Uruguay"},
  {"id": 78, "name": "Venezuela", "value": "Venezuela"},
  {"id": 79, "name": "Greenland", "value": "Greenland"},
  {"id": 80, "name": "Palestine", "value": "Palestine"},
  {"id": 81, "name": "Jordan", "value": "Jordan"},
  {"id": 82, "name": "Lebanon", "value": "Lebanon"},
  {"id": 83, "name": "Syria", "value": "Syria"},
  {"id": 84, "name": "Iraq", "value": "Iraq"}
]
